---
- name: using yum module
  yum:
     name: httpd
     state: present
- name: copying
  copy:
     src: /root/index.html
     dest: /var/www/html/index.html
     remote_src: yes
- name: managing services
  service:
     name: httpd
     state: restarted
# tasks file for apache
